/**
 * Bit2Me TOTP (2FA) Configuration Module
 *
 * This script completes the TOTP (Time-based One-Time Password) setup
 * by verifying the TOTP code generated by the authenticator app.
 *
 * @module setTOTP
 * @author Bit2Me
 */
const axios = require('axios');
const { getAuthHeaders } = require('./bit2me_logic/utils');

const ENDPOINT = process.env.END_TOTP;

const args = process.argv.slice(2);

if(args.length < 2){
    console.error("Usage: npm run set-2fa <subaccount-id> <TOTP>");
    process.exit(1);
}

const SUBACCOUNT = args[0];
const TOTP = args[1];

/**
 * Completes TOTP (2FA) setup by verifying the TOTP code
 *
 * This function finalizes the two-factor authentication setup by
 * validating that the TOTP code generated by the authenticator app
 * matches the expected value.
 *
 * @async
 * @function setTOTP
 * @param {string} subaccount - Subaccount ID for 2FA setup
 * @param {string} totp - TOTP code from authenticator app
 * @returns {Promise<Object>} TOTP configuration result
 *
 * @example
 * // Complete TOTP setup for subaccount
 * const result = await setTOTP('subaccount-123', '123456');
 *
 * @example
 * // Response structure:
 * // {
 * //   result: true, // or false if verification failed
 * //   message: 'TOTP setup completed successfully'
 * // }
 */
const setTOTP = async () => {
    try {
        // Prepare TOTP verification request
        const body = {
            "totp": TOTP
        };

        // Send TOTP verification request
        const response = await axios.post(
            `${process.env.SERVER}${ENDPOINT}`,
            body,
            getAuthHeaders(ENDPOINT, SUBACCOUNT, body)
        );

        console.log("TOTP Setup Result:");
        console.log(response.data);

        if (response.data.result) {
            console.log("\n✅ Two-factor authentication has been successfully configured!");
            console.log("Your account is now more secure with 2FA protection.");
        } else {
            console.log("\n❌ TOTP verification failed. Please try again.");
            console.log("Make sure you're using the current code from your authenticator app.");
        }

        return response.data;
    } catch (error) {
        console.error('Error completing TOTP setup:', error.response?.data || error.message);
        console.log("\nNote: If you continue to have issues, the TOTP secret may have expired.");
        console.log("Generate a new secret with: npm run get-totp <subaccount-id>");
    }
};

// Execute setTOTP if run directly
if (require.main === module) {
    setTOTP();
}

module.exports = { setTOTP };